#!/usr/bin/env python

from tasks.cache import cache_issues, cache_pulls, oldest_issues, oldest_pulls
from tasks.cache import least_issues, least_pulls, issues_closed_since


cache_issues()
cache_pulls()
oldest_issues()
oldest_pulls()
least_issues()
least_pulls()

issues_closed_since(start=0, days=7)
issues_closed_since(start=7, days=14) 

